export const ACTION_LABELS: Record<string, string> = {
  chat_message: "Career chatbot message",
  resume_skills: "Resume skill extraction",
  resume_analysis: "Full resume analysis",
  assessment_questions: "Skill assessment (10 questions)",
  learning_path: "Personalised learning path",
  interview_questions: "Mock interview questions",
  interview_evaluation: "Mock interview feedback report",
  job_match_per_resume: "Job match (per resume)",
  career_recommendations: "Career path recommendations",
  market_insights: "Job market report",
  target_role_setup: "Target role scorecard",
  deep_interview_start: "Defend-your-resume interview",
  deep_interview_report: "Defend-your-resume report",
  resume_tailor: "Tailored resume (with Word/PDF export)",
  letter: "Cover letter or outreach message",
  negotiation_start: "Salary negotiation practice",
  negotiation_report: "Salary negotiation debrief",
  proof_assessment: "Skill proof (timed, adaptive test)",
  project_review: "GitHub project review",
  prep_kit: "Interview prep kit for an application",
  aptitude_test: "Aptitude test with AI-written questions",
  code_review: "Interviewer-style code review",
  story_draft: "STAR stories drafted from your resume",
  story_critique: "STAR story critique",
  story_drill: "Behavioral drill feedback",
};

export const COMPANY_NAME = import.meta.env.VITE_COMPANY_NAME || "Skill Sphere";
export const SUPPORT_EMAIL = import.meta.env.VITE_SUPPORT_EMAIL || "support@example.com";
