/*
 * Baseline legal pages required by payment processors.
 * IMPORTANT: have these reviewed for your jurisdiction before launch, and set
 * VITE_COMPANY_NAME / VITE_SUPPORT_EMAIL at build time.
 */
import React from "react";
import { Link } from "react-router-dom";
import { COMPANY_NAME, SUPPORT_EMAIL } from "@/lib/pricing";

const UPDATED = "October 2026";

const Shell: React.FC<{ title: string; children: React.ReactNode }> = ({ title, children }) => (
  <div className="min-h-screen bg-gray-50 py-12 px-4">
    <article className="max-w-3xl mx-auto bg-white rounded-xl shadow-sm p-8 prose prose-slate">
      <Link to="/" className="no-underline text-primary font-bold">
        ← {COMPANY_NAME}
      </Link>
      <h1>{title}</h1>
      <p className="text-sm text-gray-500">Last updated: {UPDATED}</p>
      {children}
      <hr />
      <p>
        Questions? Contact us at <a href={`mailto:${SUPPORT_EMAIL}`}>{SUPPORT_EMAIL}</a>.
      </p>
      <p className="text-sm">
        <Link to="/terms">Terms</Link> · <Link to="/privacy">Privacy</Link> · <Link to="/refunds">Refunds</Link>
      </p>
    </article>
  </div>
);

export const Terms = () => (
  <Shell title="Terms of Service">
    <p>
      These terms govern your use of {COMPANY_NAME} (the "Service"). By creating an account you agree to them.
    </p>
    <h2>1. The Service</h2>
    <p>
      {COMPANY_NAME} provides AI-generated career guidance: resume feedback, skill assessments, mock interviews,
      job-match analysis, learning recommendations and job-market insights. Output is generated by AI models. It
      may contain mistakes, and it is not professional, legal or financial advice. Salary and market figures labelled
      as AI estimates are approximations, not guarantees. We do not guarantee any employment outcome.
    </p>
    <h2>2. Accounts</h2>
    <p>
      You must provide accurate information and keep your password secure. You are responsible for activity on your
      account. You must be at least 16 years old to use the Service.
    </p>
    <h2>3. Credits and payment</h2>
    <p>
      Paid features consume prepaid credits. Prices and credit costs are shown before purchase on the Billing page.
      Payments are processed by Stripe. Credits have no cash value, are non-transferable and do not expire while your
      account is active. If a request fails, the credits for it are automatically returned.
    </p>
    <h2>4. Acceptable use</h2>
    <p>
      Do not upload content you have no right to share, use the Service to discriminate unlawfully against job
      candidates, attempt to disrupt or reverse-engineer the Service, or use automated means to access it. If you
      upload other people's resumes (for example as a recruiter), you are responsible for having a lawful basis to do so.
    </p>
    <h2>5. Your content</h2>
    <p>
      You keep ownership of the content you upload. You grant us a limited licence to process it solely to provide the
      Service, as described in our Privacy Policy.
    </p>
    <h2>6. Termination</h2>
    <p>
      You may close your account at any time by contacting us. We may suspend accounts that violate these terms.
    </p>
    <h2>7. Liability</h2>
    <p>
      To the maximum extent permitted by law, the Service is provided "as is", and our total liability is limited to
      the amount you paid us in the 12 months before the claim.
    </p>
    <h2>8. Changes</h2>
    <p>We may update these terms. We will notify you of material changes by email or in the app.</p>
  </Shell>
);

export const Privacy = () => (
  <Shell title="Privacy Policy">
    <h2>What we collect</h2>
    <ul>
      <li>
        <strong>Account data:</strong> name, email address and a securely hashed password.
      </li>
      <li>
        <strong>Content you submit:</strong> resumes, job descriptions, assessment answers, interview answers and chat
        messages.
      </li>
      <li>
        <strong>Billing data:</strong> purchase history. Card details are handled entirely by Stripe and never reach
        our servers.
      </li>
      <li>
        <strong>Usage data:</strong> which features you use and how many credits they consume.
      </li>
    </ul>
    <h2>How we use it</h2>
    <p>
      Only to provide and improve the Service, process payments, prevent abuse and support you. We do not sell your
      data or use it for advertising.
    </p>
    <h2>AI processing</h2>
    <p>
      To generate results, your submitted content is sent to our AI provider, OpenAI, through their API. Under
      OpenAI's API terms, API data is not used to train their models. We ask OpenAI not to store responses.
    </p>
    <h2>Retention</h2>
    <ul>
      <li>Uploaded resume files are processed in memory and are not stored on our servers.</li>
      <li>Mock-interview results are saved to your account so you can review them, until you ask us to delete them.</li>
      <li>
        For "Defend your resume" interviews we store only the short resume lines the interviewer asks about, your
        answers and the feedback, never the full resume.
      </li>
      <li>
        Target roles (title and job description), assessment questions and results, and the readiness scores derived
        from your activity are saved to your account so you can track progress.
      </li>
      <li>
        Tailored resumes you create (including the contact details on them and the job description used) are saved to
        your account so you can edit and download them. You can delete them at any time from the Resume Tailor page.
      </li>
      <li>Salary-negotiation practice sessions (your messages and the debrief) are saved so you can review them.</li>
      <li>Chat conversations and generated cover letters or outreach messages are not stored on our servers.</li>
      <li>Account and billing records are kept while your account is active and as required by law.</li>
    </ul>
    <h2>Your rights</h2>
    <p>
      You can ask us to access, correct, export or delete your data at any time by emailing us. Depending on where you
      live (for example under the GDPR or the Indian DPDP Act), you may have additional rights.
    </p>
    <h2>Security</h2>
    <p>
      We use encrypted connections (HTTPS), hashed passwords, httpOnly session cookies and strict access controls.
    </p>
  </Shell>
);

export const Refunds = () => (
  <Shell title="Refund Policy">
    <ul>
      <li>
        <strong>Failed requests:</strong> if an AI request fails, its credits are automatically returned to your
        balance.
      </li>
      <li>
        <strong>Unused credits:</strong> you can request a refund for an unused credit pack within 14 days of
        purchase.
      </li>
      <li>
        <strong>Quality issues:</strong> if a result was clearly broken or unusable, contact us with details and we
        will restore the credits.
      </li>
      <li>Refunds go back to the original payment method, usually within 5–10 business days.</li>
    </ul>
  </Shell>
);
